#!/usr/bin/env python
from _base import debugLogger
from _base import masterLogger
from _django import Django


def main():
    debugLogger("test debug")
    masterLogger("test master")
    d = Django()
    d.deploy()


if __name__ == '__main__':
    main()
