#!/usr/bin/env python
from _base import debugLogger
from _base import masterLogger
from _base import Deployment  # do not remove
from _base import unpickle_deployment


def main():
    deployment = unpickle_deployment()
    debugLogger("Unpickled deployment data")

    out, err = deployment.start_applications()
    debugLogger("Started applications stdout: %s" % out)
    debugLogger("Started applications stderr: %s" % err)

    out, err = deployment.start_performance_measurements()
    debugLogger("Started performance measurements: %s" % out)
    debugLogger("Started performance measurements: %s" % err)

    out, err = deployment.start_benchmark_client()
    debugLogger("Benchmark results stdout: %s" % out)
    debugLogger("Benchmark results stderr: %s" % err)
    masterLogger("Benchmark results: %s %s" % (out, err))

    out, err = deployment.stop_benchmark_client()
    debugLogger("Stopped benchmark stdout: %s" % out)
    debugLogger("Stopped benchmark stderr: %s" % err)

    out, err = deployment.stop_performance_measurements()
    debugLogger("Stopped performance measurements: %s" % out)
    debugLogger("Stopped performance measurements: %s" % err)

    out, err = deployment.stop_applications()
    debugLogger("Stopped applications stdout: %s" % out)
    debugLogger("Stopped applications stderr: %s" % err)

    deployment.collect_performance_data()


if __name__ == '__main__':
    main()
