#!/usr/bin/env python
import os


def main():
    #TODO add a cleanup method in _base.Deployment
    os.system('rm -f .host.setup.done')
    os.system('rm -f .deployment.pickle')
    os.system('rm -f *.log')
    os.system('rm -rf measurements')
    os.system('rm -rf myperf.data')


if __name__ == '__main__':
    main()
