#!/usr/bin/env python
from _base import parse_undeploy_args
import os


def main():
    parse_undeploy_args()

    #TODO add a cleanup method in _base.Deployment
    os.system('rm -f .host.setup.done')
    os.system('rm -f /tmp/.host.reboot.required')
    os.system('rm -f .deployment.pickle')
    os.system('rm -f *.log')
    os.system('rm -rf measurements')


if __name__ == '__main__':
    main()
