#!/bin/bash

if [ $# -lt 2 ]
then
    echo "Usage: ./_create_app APPNAME DISTRIBUTION"
    echo "Example: ./_create_app cassandra ubuntu"
    exit
fi

APP=$1
DISTRIBUTION=$2

mkdir -p ${APP}/${DISTRIBUTION}
echo "Created ${APP}/${DISTRIBUTION}"

content="#!/bin/bash

###############################################################################
# Environment data
###############################################################################


###############################################################################
# Commands
###############################################################################

"

echo "$content" > ${APP}/${DISTRIBUTION}/deploy.sh
echo "$content" >  ${APP}/${DISTRIBUTION}/undeploy.sh
echo "$content" >  ${APP}/${DISTRIBUTION}/start.sh
echo "$content" >  ${APP}/${DISTRIBUTION}/stop.sh
echo "Created stub scripts"

chmod +x ${APP}/${DISTRIBUTION}/*.sh
echo "Done!"