#!/bin/bash

if [ $# -lt 2 ]
then
    echo "Usage: ./_create_app APPNAME DISTRIBUTION"
    echo "Example: ./_create_app cassandra ubuntu"
    exit
fi

APP=$1
DISTRIBUTION=$2

mkdir -p ${APP}/${DISTRIBUTION}
echo "Created ${APP}/${DISTRIBUTION}"

echo -e "#!/bin/bash\n" > ${APP}/${DISTRIBUTION}/deploy.sh
echo -e "#!/bin/bash\n" >  ${APP}/${DISTRIBUTION}/undeploy.sh
echo -e "#!/bin/bash\n" >  ${APP}/${DISTRIBUTION}/start.sh
echo -e "#!/bin/bash\n" >  ${APP}/${DISTRIBUTION}/stop.sh
echo "Created stub scripts"

chmod +x ${APP}/${DISTRIBUTION}/*.sh
echo "Done!"